title: "xf_blog"

author:      
  name: lm-xiao-fen      
  email: your-email@domain.com        

description: >
  xiaofen’s jekyll blog    

baseurl: ""
url: "https://lm-xiao-fen.github.io"      

remote_theme: "jekyll/minima@1e8a445"
# remote_theme: pages-themes/primer@v0.6.0          

collections:    
  note:
    output: true  

minima:
  skin: classic

nav_pages:               
    - note.md          
    - tech.md            

plugins:    
  - jekyll-feed
  - jekyll-seo-tag  

sass:  
  quiet_deps: true        
  silence_deprecations: [import]
